### ISSUE TITLE
Can't block YouTube ads?

### ISSUE THREAD

**Issue by yyms3275** [marcelbohland/Android-Webview-Adblock-Example#2]
When I visit the YouTube site, an ad appears, can I not block it? Video ads.

**Comment by marcelbohland** [comment]
Youtube uses an algorithm to block advertising. With filter lists, it is relatively difficult to block advertising on YouTube. But there are filter lists that can possibly block a large part of the advertisements. You can try to add the following lists.

https://github.com/kboghdady/youTube_ads_4_pi-hole
https://www.sunshine.it/blacklist.txt
https://raw.githubusercontent.com/Ewpratten/youtube_ad_blocklist/master/blocklist.txt

**Comment by Eyal-Elbaz** [comment]
Can I enter those list to yours webview or should I modify them?

Thanks a lot!
